language: php

services: mysql

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

script:
  - composer tests

jobs:
  include:
    - stage: prime versions
      php: 8.0
      env:
        - PRIME_VERSION="~1.2.0"
        - PRIME_VERSION="~1.3.0"
        - PRIME_VERSION="~2.0.0"
      script:
        - composer require "b2pweb/bdf-prime:$PRIME_VERSION" --with-all-dependencies
        - composer tests
